/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AlertRequestConditions {
    /**
    * Types: 1-Price, 3-Time, 4-Margin, 5-Trade, 6-Volume, 7: MTA market 8: MTA Position, 9: MTA Acc. Daily PN& 
    */
    'type'?: number;
    /**
    * format, conid@exchange
    */
    'conidex'?: string;
    /**
    * optional, operator for the current condition, can be >= or <=
    */
    'operator'?: string;
    /**
    * optional, only some type of conditions have triggerMethod
    */
    'triggerMethod'?: string;
    /**
    * can not be empty, can pass default value \"*\"
    */
    'value'?: string;
    /**
    * \"a\" means \"AND\", \"o\" means \"OR\", \"n\" means \"END\", the last one condition in the condition array should \"n\" 
    */
    'logicBind'?: string;
    /**
    * only needed for some MTA alert condition
    */
    'timeZone'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "number"
        },
        {
            "name": "conidex",
            "baseName": "conidex",
            "type": "string"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "string"
        },
        {
            "name": "triggerMethod",
            "baseName": "triggerMethod",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "logicBind",
            "baseName": "logicBind",
            "type": "string"
        },
        {
            "name": "timeZone",
            "baseName": "timeZone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AlertRequestConditions.attributeTypeMap;
    }
}

