/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AuthStatus {
    /**
    * Brokerage session is authenticated
    */
    'authenticated'?: boolean;
    /**
    * Connected to backend
    */
    'connected'?: boolean;
    /**
    * Brokerage session is competing, e.g. user is logged in to IBKR Mobile, WebTrader, TWS or other trading platforms.
    */
    'competing'?: boolean;
    /**
    * Authentication failed, why.
    */
    'fail'?: string;
    /**
    * System messages that may affect trading
    */
    'message'?: string;
    /**
    * Prompt messages that may affect trading or the account
    */
    'prompts'?: Array<string>;

    'error'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "authenticated",
            "baseName": "authenticated",
            "type": "boolean"
        },
        {
            "name": "connected",
            "baseName": "connected",
            "type": "boolean"
        },
        {
            "name": "competing",
            "baseName": "competing",
            "type": "boolean"
        },
        {
            "name": "fail",
            "baseName": "fail",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "prompts",
            "baseName": "prompts",
            "type": "Array<string>"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        }
    ];

    static getAttributeTypeMap() {
        return AuthStatus.attributeTypeMap;
    }
}
