/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CalendarRequestDate } from './calendarRequestDate';
import { CalendarRequestFilters } from './calendarRequestFilters';

export class CalendarRequest {
    'date'?: CalendarRequestDate;
    'filters'?: CalendarRequestFilters;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "CalendarRequestDate"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "CalendarRequestFilters"
        }    ];

    static getAttributeTypeMap() {
        return CalendarRequest.attributeTypeMap;
    }
}

