/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CalendarRequestFilters {
    /**
    * value can be \'true\' or \'false\'.
    */
    'recently_held'?: string;
    /**
    * value can be \'true\' or \'false\'.
    */
    'corporate_earnings'?: string;
    /**
    * value can be \'true\' or \'false\'.
    */
    'DivExDates'?: string;
    /**
    * value can be \'true\' or \'false\'.
    */
    'ipo'?: string;
    /**
    * value can be \'true\' or \'false\'.
    */
    'splits'?: string;
    /**
    * value can be \'true\' or \'false\'.
    */
    'corporate_events'?: string;
    /**
    * value can be \'true\' or \'false\'.
    */
    'economic_events'?: string;
    /**
    * value can be \'true\' or \'false\'.
    */
    'option_show_monthly'?: string;
    /**
    * value can be \'true\' or \'false\'.
    */
    'option_show_weekly'?: string;
    /**
    * default is \'All\'.
    */
    'country'?: string;
    /**
    * default is \'250\'.
    */
    'limit'?: string;
    /**
    * default is \'50\'.
    */
    'limit_region'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recently_held",
            "baseName": "recently_held",
            "type": "string"
        },
        {
            "name": "corporate_earnings",
            "baseName": "corporate_earnings",
            "type": "string"
        },
        {
            "name": "DivExDates",
            "baseName": "DivExDates",
            "type": "string"
        },
        {
            "name": "ipo",
            "baseName": "ipo",
            "type": "string"
        },
        {
            "name": "splits",
            "baseName": "splits",
            "type": "string"
        },
        {
            "name": "corporate_events",
            "baseName": "corporate_events",
            "type": "string"
        },
        {
            "name": "economic_events",
            "baseName": "economic_events",
            "type": "string"
        },
        {
            "name": "option_show_monthly",
            "baseName": "option_show_monthly",
            "type": "string"
        },
        {
            "name": "option_show_weekly",
            "baseName": "option_show_weekly",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "string"
        },
        {
            "name": "limit_region",
            "baseName": "limit_region",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CalendarRequestFilters.attributeTypeMap;
    }
}

