/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ContractRules {
    'orderTypes'?: Array<string>;
    'orderTypesOutside'?: Array<string>;
    /**
    * default quantity you can use to place an order
    */
    'defaultSize'?: number;
    'sizeIncrement'?: number;
    'tifTypes'?: Array<string>;
    /**
    * default limit price you can use to prefill your order
    */
    'limitPrice'?: number;
    /**
    * default stop price you can use to prefill your order
    */
    'stopprice'?: number;
    /**
    * if you can preview the order or not with the whatif endpoint
    */
    'preview'?: boolean;
    'displaySize'?: string;
    'increment'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderTypes",
            "baseName": "orderTypes",
            "type": "Array<string>"
        },
        {
            "name": "orderTypesOutside",
            "baseName": "orderTypesOutside",
            "type": "Array<string>"
        },
        {
            "name": "defaultSize",
            "baseName": "defaultSize",
            "type": "number"
        },
        {
            "name": "sizeIncrement",
            "baseName": "sizeIncrement",
            "type": "number"
        },
        {
            "name": "tifTypes",
            "baseName": "tifTypes",
            "type": "Array<string>"
        },
        {
            "name": "limitPrice",
            "baseName": "limitPrice",
            "type": "number"
        },
        {
            "name": "stopprice",
            "baseName": "stopprice",
            "type": "number"
        },
        {
            "name": "preview",
            "baseName": "preview",
            "type": "boolean"
        },
        {
            "name": "displaySize",
            "baseName": "displaySize",
            "type": "string"
        },
        {
            "name": "increment",
            "baseName": "increment",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ContractRules.attributeTypeMap;
    }
}

