/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InlineResponse20035Sessions } from './inlineResponse20035Sessions';
import { InlineResponse20035TradingTimes } from './inlineResponse20035TradingTimes';

export class InlineResponse20035Schedules {
    'clearingCycleEndTime'?: number;
    /**
    * 20000101 stands for any Sat, 20000102 stands for any Sun, ... 20000107 stands for any Fri. Any other date stands for itself.
    */
    'tradingScheduleDate'?: number;
    'sessions'?: InlineResponse20035Sessions;
    'tradingTimes'?: InlineResponse20035TradingTimes;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clearingCycleEndTime",
            "baseName": "clearingCycleEndTime",
            "type": "number"
        },
        {
            "name": "tradingScheduleDate",
            "baseName": "tradingScheduleDate",
            "type": "number"
        },
        {
            "name": "sessions",
            "baseName": "sessions",
            "type": "InlineResponse20035Sessions"
        },
        {
            "name": "tradingTimes",
            "baseName": "tradingTimes",
            "type": "InlineResponse20035TradingTimes"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20035Schedules.attributeTypeMap;
    }
}

