/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse20011 {
    /**
    * 1 for Live, 2 for Paper
    */
    'LOGIN_TYPE'?: number;
    /**
    * Username
    */
    'USER_NAME'?: string;
    /**
    * User ID
    */
    'USER_ID'?: number;
    /**
    * Time in milliseconds until session expires. Caller needs to call the again to re-validate session
    */
    'expire'?: number;
    /**
    * true if session was validated; false if not.
    */
    'RESULT'?: boolean;
    /**
    * Time of session validation
    */
    'AUTH_TIME'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "LOGIN_TYPE",
            "baseName": "LOGIN_TYPE",
            "type": "number"
        },
        {
            "name": "USER_NAME",
            "baseName": "USER_NAME",
            "type": "string"
        },
        {
            "name": "USER_ID",
            "baseName": "USER_ID",
            "type": "number"
        },
        {
            "name": "expire",
            "baseName": "expire",
            "type": "number"
        },
        {
            "name": "RESULT",
            "baseName": "RESULT",
            "type": "boolean"
        },
        {
            "name": "AUTH_TIME",
            "baseName": "AUTH_TIME",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20011.attributeTypeMap;
    }
}

