/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject10 {
    /**
    * answer to question, true means yes, false means no
    */
    'confirmed'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "confirmed",
            "baseName": "confirmed",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject10.attributeTypeMap;
    }
}

