/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse20030 {
    'call'?: Array<string>;
    'put'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "call",
            "baseName": "call",
            "type": "Array<string>"
        },
        {
            "name": "put",
            "baseName": "put",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20030.attributeTypeMap;
    }
}

