/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject3 {
    'acctIds'?: Array<string>;
    /**
    * Frequency of cumulative performance data points: \'D\'aily, \'M\'onthly,\'Q\'uarterly. 
    */
    'freq'?: InlineObject3.FreqEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "acctIds",
            "baseName": "acctIds",
            "type": "Array<string>"
        },
        {
            "name": "freq",
            "baseName": "freq",
            "type": "InlineObject3.FreqEnum"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject3.attributeTypeMap;
    }
}

export namespace InlineObject3 {
    export enum FreqEnum {
        D = <any> 'D',
        M = <any> 'M',
        Q = <any> 'Q'
    }
}
