/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InlineResponse2004E } from './inlineResponse2004E';

export class InlineResponse2004 {
    /**
    * Email option is enabled or not 0-off, 1-on.
    */
    'M'?: number;
    'E'?: Array<InlineResponse2004E>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "M",
            "baseName": "M",
            "type": "number"
        },
        {
            "name": "E",
            "baseName": "E",
            "type": "Array<InlineResponse2004E>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2004.attributeTypeMap;
    }
}

