/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IserverSecdefSearchSections } from './iserverSecdefSearchSections';

export class InlineResponse20029 {
    /**
    * Contract Identifier
    */
    'conid'?: number;
    /**
    * Company Name - Exchange
    */
    'companyHeader'?: string;
    'companyName'?: string;
    'symbol'?: string;
    /**
    * Exchange
    */
    'description'?: string;
    'restricted'?: string;
    'fop'?: string;
    'opt'?: string;
    'war'?: string;
    'sections'?: Array<IserverSecdefSearchSections>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conid",
            "baseName": "conid",
            "type": "number"
        },
        {
            "name": "companyHeader",
            "baseName": "companyHeader",
            "type": "string"
        },
        {
            "name": "companyName",
            "baseName": "companyName",
            "type": "string"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "restricted",
            "baseName": "restricted",
            "type": "string"
        },
        {
            "name": "fop",
            "baseName": "fop",
            "type": "string"
        },
        {
            "name": "opt",
            "baseName": "opt",
            "type": "string"
        },
        {
            "name": "war",
            "baseName": "war",
            "type": "string"
        },
        {
            "name": "sections",
            "baseName": "sections",
            "type": "Array<IserverSecdefSearchSections>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20029.attributeTypeMap;
    }
}

