/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InlineResponse20031String } from './inlineResponse20031String';

export class InlineResponse20031OrderDefaults {
    /**
    * orderType
    */
    'string'?: Array<InlineResponse20031String>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "string",
            "baseName": "string",
            "type": "Array<InlineResponse20031String>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20031OrderDefaults.attributeTypeMap;
    }
}

