/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Summary } from './summary';

export class InlineResponse20012 {
    'accountready'?: Summary;
    'accounttype'?: Summary;
    'accruedcash'?: Summary;
    'accruedcash_c'?: Summary;
    'accruedcash_f'?: Summary;
    'accruedcash_s'?: Summary;
    'accrueddividend'?: Summary;
    'accrueddividend_c'?: Summary;
    'accrueddividend_f'?: Summary;
    'accrueddividend_s'?: Summary;
    'availablefunds'?: Summary;
    'availablefunds_c'?: Summary;
    'availablefunds_f'?: Summary;
    'availablefunds_s'?: Summary;
    'billable'?: Summary;
    'billable_c'?: Summary;
    'billable_f'?: Summary;
    'billable_s'?: Summary;
    'buyingpower'?: Summary;
    'cushion'?: Summary;
    'daytradesremaining'?: Summary;
    'daytradesremainingt1'?: Summary;
    'daytradesremainingt2'?: Summary;
    'daytradesremainingt3'?: Summary;
    'daytradesremainingt4'?: Summary;
    'equitywithloanvalue'?: Summary;
    'equitywithloanvalue_c'?: Summary;
    'equitywithloanvalue_f'?: Summary;
    'equitywithloanvalue_s'?: Summary;
    'excessliquidity'?: Summary;
    'excessliquidity_c'?: Summary;
    'excessliquidity_f'?: Summary;
    'excessliquidity_s'?: Summary;
    'fullavailablefunds'?: Summary;
    'fullavailablefunds_c'?: Summary;
    'fullavailablefunds_f'?: Summary;
    'fullavailablefunds_s'?: Summary;
    'fullexcessliquidity'?: Summary;
    'fullexcessliquidity_c'?: Summary;
    'fullexcessliquidity_f'?: Summary;
    'fullexcessliquidity_s'?: Summary;
    'fullinitmarginreq'?: Summary;
    'fullinitmarginreq_c'?: Summary;
    'fullinitmarginreq_f'?: Summary;
    'fullinitmarginreq_s'?: Summary;
    'fullmaintmarginreq'?: Summary;
    'fullmaintmarginreq_c'?: Summary;
    'fullmaintmarginreq_f'?: Summary;
    'fullmaintmarginreq_s'?: Summary;
    'grosspositionvalue'?: Summary;
    'grosspositionvalue_c'?: Summary;
    'grosspositionvalue_f'?: Summary;
    'grosspositionvalue_s'?: Summary;
    'guarantee'?: Summary;
    'guarantee_c'?: Summary;
    'guarantee_f'?: Summary;
    'guarantee_s'?: Summary;
    'highestseverity'?: Summary;
    'highestseverity_c'?: Summary;
    'highestseverity_f'?: Summary;
    'highestseverity_s'?: Summary;
    'indianstockhaircut'?: Summary;
    'indianstockhaircut_c'?: Summary;
    'indianstockhaircut_f'?: Summary;
    'indianstockhaircut_s'?: Summary;
    'initmarginreq'?: Summary;
    'initmarginreq_c'?: Summary;
    'initmarginreq_f'?: Summary;
    'initmarginreq_s'?: Summary;
    'leverage'?: Summary;
    'leverage_c'?: Summary;
    'leverage_f'?: Summary;
    'leverage_s'?: Summary;
    'lookaheadavailablefunds'?: Summary;
    'lookaheadavailablefunds_c'?: Summary;
    'lookaheadavailablefunds_f'?: Summary;
    'lookaheadavailablefunds_s'?: Summary;
    'lookaheadexcessliquidity'?: Summary;
    'lookaheadexcessliquidity_c'?: Summary;
    'lookaheadexcessliquidity_f'?: Summary;
    'lookaheadexcessliquidity_s'?: Summary;
    'lookaheadinitmarginreq'?: Summary;
    'lookaheadinitmarginreq_c'?: Summary;
    'lookaheadinitmarginreq_f'?: Summary;
    'lookaheadinitmarginreq_s'?: Summary;
    'lookaheadmaintmarginreq'?: Summary;
    'lookaheadmaintmarginreq_c'?: Summary;
    'lookaheadmaintmarginreq_f'?: Summary;
    'lookaheadmaintmarginreq_s'?: Summary;
    'lookaheadnextchange'?: Summary;
    'maintmarginreq'?: Summary;
    'maintmarginreq_c'?: Summary;
    'maintmarginreq_f'?: Summary;
    'maintmarginreq_s'?: Summary;
    'netliquidation'?: Summary;
    'netliquidation_c'?: Summary;
    'netliquidation_f'?: Summary;
    'netliquidation_s'?: Summary;
    'netliquidationuncertainty'?: Summary;
    'nlvandmargininreview'?: Summary;
    'pasharesvalue'?: Summary;
    'pasharesvalue_c'?: Summary;
    'pasharesvalue_f'?: Summary;
    'pasharesvalue_s'?: Summary;
    'postexpirationexcess'?: Summary;
    'postexpirationexcess_c'?: Summary;
    'postexpirationexcess_f'?: Summary;
    'postexpirationexcess_s'?: Summary;
    'postexpirationmargin'?: Summary;
    'postexpirationmargin_c'?: Summary;
    'postexpirationmargin_f'?: Summary;
    'postexpirationmargin_s'?: Summary;
    'previousdayequitywithloanvalue'?: Summary;
    'previousdayequitywithloanvalue_c'?: Summary;
    'previousdayequitywithloanvalue_f'?: Summary;
    'previousdayequitywithloanvalue_s'?: Summary;
    'segmenttitle_c'?: Summary;
    'segmenttitle_f'?: Summary;
    'segmenttitle_s'?: Summary;
    'totalcashvalue'?: Summary;
    'totalcashvalue_c'?: Summary;
    'totalcashvalue_f'?: Summary;
    'totalcashvalue_s'?: Summary;
    'totaldebitcardpendingcharges'?: Summary;
    'totaldebitcardpendingcharges_c'?: Summary;
    'totaldebitcardpendingcharges_f'?: Summary;
    'totaldebitcardpendingcharges_s'?: Summary;
    'tradingtype_f'?: Summary;
    'tradingtype_s'?: Summary;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountready",
            "baseName": "accountready",
            "type": "Summary"
        },
        {
            "name": "accounttype",
            "baseName": "accounttype",
            "type": "Summary"
        },
        {
            "name": "accruedcash",
            "baseName": "accruedcash",
            "type": "Summary"
        },
        {
            "name": "accruedcash_c",
            "baseName": "accruedcash-c",
            "type": "Summary"
        },
        {
            "name": "accruedcash_f",
            "baseName": "accruedcash-f",
            "type": "Summary"
        },
        {
            "name": "accruedcash_s",
            "baseName": "accruedcash-s",
            "type": "Summary"
        },
        {
            "name": "accrueddividend",
            "baseName": "accrueddividend",
            "type": "Summary"
        },
        {
            "name": "accrueddividend_c",
            "baseName": "accrueddividend-c",
            "type": "Summary"
        },
        {
            "name": "accrueddividend_f",
            "baseName": "accrueddividend-f",
            "type": "Summary"
        },
        {
            "name": "accrueddividend_s",
            "baseName": "accrueddividend-s",
            "type": "Summary"
        },
        {
            "name": "availablefunds",
            "baseName": "availablefunds",
            "type": "Summary"
        },
        {
            "name": "availablefunds_c",
            "baseName": "availablefunds-c",
            "type": "Summary"
        },
        {
            "name": "availablefunds_f",
            "baseName": "availablefunds-f",
            "type": "Summary"
        },
        {
            "name": "availablefunds_s",
            "baseName": "availablefunds-s",
            "type": "Summary"
        },
        {
            "name": "billable",
            "baseName": "billable",
            "type": "Summary"
        },
        {
            "name": "billable_c",
            "baseName": "billable-c",
            "type": "Summary"
        },
        {
            "name": "billable_f",
            "baseName": "billable-f",
            "type": "Summary"
        },
        {
            "name": "billable_s",
            "baseName": "billable-s",
            "type": "Summary"
        },
        {
            "name": "buyingpower",
            "baseName": "buyingpower",
            "type": "Summary"
        },
        {
            "name": "cushion",
            "baseName": "cushion",
            "type": "Summary"
        },
        {
            "name": "daytradesremaining",
            "baseName": "daytradesremaining",
            "type": "Summary"
        },
        {
            "name": "daytradesremainingt1",
            "baseName": "daytradesremainingt+1",
            "type": "Summary"
        },
        {
            "name": "daytradesremainingt2",
            "baseName": "daytradesremainingt+2",
            "type": "Summary"
        },
        {
            "name": "daytradesremainingt3",
            "baseName": "daytradesremainingt+3",
            "type": "Summary"
        },
        {
            "name": "daytradesremainingt4",
            "baseName": "daytradesremainingt+4",
            "type": "Summary"
        },
        {
            "name": "equitywithloanvalue",
            "baseName": "equitywithloanvalue",
            "type": "Summary"
        },
        {
            "name": "equitywithloanvalue_c",
            "baseName": "equitywithloanvalue-c",
            "type": "Summary"
        },
        {
            "name": "equitywithloanvalue_f",
            "baseName": "equitywithloanvalue-f",
            "type": "Summary"
        },
        {
            "name": "equitywithloanvalue_s",
            "baseName": "equitywithloanvalue-s",
            "type": "Summary"
        },
        {
            "name": "excessliquidity",
            "baseName": "excessliquidity",
            "type": "Summary"
        },
        {
            "name": "excessliquidity_c",
            "baseName": "excessliquidity-c",
            "type": "Summary"
        },
        {
            "name": "excessliquidity_f",
            "baseName": "excessliquidity-f",
            "type": "Summary"
        },
        {
            "name": "excessliquidity_s",
            "baseName": "excessliquidity-s",
            "type": "Summary"
        },
        {
            "name": "fullavailablefunds",
            "baseName": "fullavailablefunds",
            "type": "Summary"
        },
        {
            "name": "fullavailablefunds_c",
            "baseName": "fullavailablefunds-c",
            "type": "Summary"
        },
        {
            "name": "fullavailablefunds_f",
            "baseName": "fullavailablefunds-f",
            "type": "Summary"
        },
        {
            "name": "fullavailablefunds_s",
            "baseName": "fullavailablefunds-s",
            "type": "Summary"
        },
        {
            "name": "fullexcessliquidity",
            "baseName": "fullexcessliquidity",
            "type": "Summary"
        },
        {
            "name": "fullexcessliquidity_c",
            "baseName": "fullexcessliquidity-c",
            "type": "Summary"
        },
        {
            "name": "fullexcessliquidity_f",
            "baseName": "fullexcessliquidity-f",
            "type": "Summary"
        },
        {
            "name": "fullexcessliquidity_s",
            "baseName": "fullexcessliquidity-s",
            "type": "Summary"
        },
        {
            "name": "fullinitmarginreq",
            "baseName": "fullinitmarginreq",
            "type": "Summary"
        },
        {
            "name": "fullinitmarginreq_c",
            "baseName": "fullinitmarginreq-c",
            "type": "Summary"
        },
        {
            "name": "fullinitmarginreq_f",
            "baseName": "fullinitmarginreq-f",
            "type": "Summary"
        },
        {
            "name": "fullinitmarginreq_s",
            "baseName": "fullinitmarginreq-s",
            "type": "Summary"
        },
        {
            "name": "fullmaintmarginreq",
            "baseName": "fullmaintmarginreq",
            "type": "Summary"
        },
        {
            "name": "fullmaintmarginreq_c",
            "baseName": "fullmaintmarginreq-c",
            "type": "Summary"
        },
        {
            "name": "fullmaintmarginreq_f",
            "baseName": "fullmaintmarginreq-f",
            "type": "Summary"
        },
        {
            "name": "fullmaintmarginreq_s",
            "baseName": "fullmaintmarginreq-s",
            "type": "Summary"
        },
        {
            "name": "grosspositionvalue",
            "baseName": "grosspositionvalue",
            "type": "Summary"
        },
        {
            "name": "grosspositionvalue_c",
            "baseName": "grosspositionvalue-c",
            "type": "Summary"
        },
        {
            "name": "grosspositionvalue_f",
            "baseName": "grosspositionvalue-f",
            "type": "Summary"
        },
        {
            "name": "grosspositionvalue_s",
            "baseName": "grosspositionvalue-s",
            "type": "Summary"
        },
        {
            "name": "guarantee",
            "baseName": "guarantee",
            "type": "Summary"
        },
        {
            "name": "guarantee_c",
            "baseName": "guarantee-c",
            "type": "Summary"
        },
        {
            "name": "guarantee_f",
            "baseName": "guarantee-f",
            "type": "Summary"
        },
        {
            "name": "guarantee_s",
            "baseName": "guarantee-s",
            "type": "Summary"
        },
        {
            "name": "highestseverity",
            "baseName": "highestseverity",
            "type": "Summary"
        },
        {
            "name": "highestseverity_c",
            "baseName": "highestseverity-c",
            "type": "Summary"
        },
        {
            "name": "highestseverity_f",
            "baseName": "highestseverity-f",
            "type": "Summary"
        },
        {
            "name": "highestseverity_s",
            "baseName": "highestseverity-s",
            "type": "Summary"
        },
        {
            "name": "indianstockhaircut",
            "baseName": "indianstockhaircut",
            "type": "Summary"
        },
        {
            "name": "indianstockhaircut_c",
            "baseName": "indianstockhaircut-c",
            "type": "Summary"
        },
        {
            "name": "indianstockhaircut_f",
            "baseName": "indianstockhaircut-f",
            "type": "Summary"
        },
        {
            "name": "indianstockhaircut_s",
            "baseName": "indianstockhaircut-s",
            "type": "Summary"
        },
        {
            "name": "initmarginreq",
            "baseName": "initmarginreq",
            "type": "Summary"
        },
        {
            "name": "initmarginreq_c",
            "baseName": "initmarginreq-c",
            "type": "Summary"
        },
        {
            "name": "initmarginreq_f",
            "baseName": "initmarginreq-f",
            "type": "Summary"
        },
        {
            "name": "initmarginreq_s",
            "baseName": "initmarginreq-s",
            "type": "Summary"
        },
        {
            "name": "leverage",
            "baseName": "leverage",
            "type": "Summary"
        },
        {
            "name": "leverage_c",
            "baseName": "leverage-c",
            "type": "Summary"
        },
        {
            "name": "leverage_f",
            "baseName": "leverage-f",
            "type": "Summary"
        },
        {
            "name": "leverage_s",
            "baseName": "leverage-s",
            "type": "Summary"
        },
        {
            "name": "lookaheadavailablefunds",
            "baseName": "lookaheadavailablefunds",
            "type": "Summary"
        },
        {
            "name": "lookaheadavailablefunds_c",
            "baseName": "lookaheadavailablefunds-c",
            "type": "Summary"
        },
        {
            "name": "lookaheadavailablefunds_f",
            "baseName": "lookaheadavailablefunds-f",
            "type": "Summary"
        },
        {
            "name": "lookaheadavailablefunds_s",
            "baseName": "lookaheadavailablefunds-s",
            "type": "Summary"
        },
        {
            "name": "lookaheadexcessliquidity",
            "baseName": "lookaheadexcessliquidity",
            "type": "Summary"
        },
        {
            "name": "lookaheadexcessliquidity_c",
            "baseName": "lookaheadexcessliquidity-c",
            "type": "Summary"
        },
        {
            "name": "lookaheadexcessliquidity_f",
            "baseName": "lookaheadexcessliquidity-f",
            "type": "Summary"
        },
        {
            "name": "lookaheadexcessliquidity_s",
            "baseName": "lookaheadexcessliquidity-s",
            "type": "Summary"
        },
        {
            "name": "lookaheadinitmarginreq",
            "baseName": "lookaheadinitmarginreq",
            "type": "Summary"
        },
        {
            "name": "lookaheadinitmarginreq_c",
            "baseName": "lookaheadinitmarginreq-c",
            "type": "Summary"
        },
        {
            "name": "lookaheadinitmarginreq_f",
            "baseName": "lookaheadinitmarginreq-f",
            "type": "Summary"
        },
        {
            "name": "lookaheadinitmarginreq_s",
            "baseName": "lookaheadinitmarginreq-s",
            "type": "Summary"
        },
        {
            "name": "lookaheadmaintmarginreq",
            "baseName": "lookaheadmaintmarginreq",
            "type": "Summary"
        },
        {
            "name": "lookaheadmaintmarginreq_c",
            "baseName": "lookaheadmaintmarginreq-c",
            "type": "Summary"
        },
        {
            "name": "lookaheadmaintmarginreq_f",
            "baseName": "lookaheadmaintmarginreq-f",
            "type": "Summary"
        },
        {
            "name": "lookaheadmaintmarginreq_s",
            "baseName": "lookaheadmaintmarginreq-s",
            "type": "Summary"
        },
        {
            "name": "lookaheadnextchange",
            "baseName": "lookaheadnextchange",
            "type": "Summary"
        },
        {
            "name": "maintmarginreq",
            "baseName": "maintmarginreq",
            "type": "Summary"
        },
        {
            "name": "maintmarginreq_c",
            "baseName": "maintmarginreq-c",
            "type": "Summary"
        },
        {
            "name": "maintmarginreq_f",
            "baseName": "maintmarginreq-f",
            "type": "Summary"
        },
        {
            "name": "maintmarginreq_s",
            "baseName": "maintmarginreq-s",
            "type": "Summary"
        },
        {
            "name": "netliquidation",
            "baseName": "netliquidation",
            "type": "Summary"
        },
        {
            "name": "netliquidation_c",
            "baseName": "netliquidation-c",
            "type": "Summary"
        },
        {
            "name": "netliquidation_f",
            "baseName": "netliquidation-f",
            "type": "Summary"
        },
        {
            "name": "netliquidation_s",
            "baseName": "netliquidation-s",
            "type": "Summary"
        },
        {
            "name": "netliquidationuncertainty",
            "baseName": "netliquidationuncertainty",
            "type": "Summary"
        },
        {
            "name": "nlvandmargininreview",
            "baseName": "nlvandmargininreview",
            "type": "Summary"
        },
        {
            "name": "pasharesvalue",
            "baseName": "pasharesvalue",
            "type": "Summary"
        },
        {
            "name": "pasharesvalue_c",
            "baseName": "pasharesvalue-c",
            "type": "Summary"
        },
        {
            "name": "pasharesvalue_f",
            "baseName": "pasharesvalue-f",
            "type": "Summary"
        },
        {
            "name": "pasharesvalue_s",
            "baseName": "pasharesvalue-s",
            "type": "Summary"
        },
        {
            "name": "postexpirationexcess",
            "baseName": "postexpirationexcess",
            "type": "Summary"
        },
        {
            "name": "postexpirationexcess_c",
            "baseName": "postexpirationexcess-c",
            "type": "Summary"
        },
        {
            "name": "postexpirationexcess_f",
            "baseName": "postexpirationexcess-f",
            "type": "Summary"
        },
        {
            "name": "postexpirationexcess_s",
            "baseName": "postexpirationexcess-s",
            "type": "Summary"
        },
        {
            "name": "postexpirationmargin",
            "baseName": "postexpirationmargin",
            "type": "Summary"
        },
        {
            "name": "postexpirationmargin_c",
            "baseName": "postexpirationmargin-c",
            "type": "Summary"
        },
        {
            "name": "postexpirationmargin_f",
            "baseName": "postexpirationmargin-f",
            "type": "Summary"
        },
        {
            "name": "postexpirationmargin_s",
            "baseName": "postexpirationmargin-s",
            "type": "Summary"
        },
        {
            "name": "previousdayequitywithloanvalue",
            "baseName": "previousdayequitywithloanvalue",
            "type": "Summary"
        },
        {
            "name": "previousdayequitywithloanvalue_c",
            "baseName": "previousdayequitywithloanvalue-c",
            "type": "Summary"
        },
        {
            "name": "previousdayequitywithloanvalue_f",
            "baseName": "previousdayequitywithloanvalue-f",
            "type": "Summary"
        },
        {
            "name": "previousdayequitywithloanvalue_s",
            "baseName": "previousdayequitywithloanvalue-s",
            "type": "Summary"
        },
        {
            "name": "segmenttitle_c",
            "baseName": "segmenttitle-c",
            "type": "Summary"
        },
        {
            "name": "segmenttitle_f",
            "baseName": "segmenttitle-f",
            "type": "Summary"
        },
        {
            "name": "segmenttitle_s",
            "baseName": "segmenttitle-s",
            "type": "Summary"
        },
        {
            "name": "totalcashvalue",
            "baseName": "totalcashvalue",
            "type": "Summary"
        },
        {
            "name": "totalcashvalue_c",
            "baseName": "totalcashvalue-c",
            "type": "Summary"
        },
        {
            "name": "totalcashvalue_f",
            "baseName": "totalcashvalue-f",
            "type": "Summary"
        },
        {
            "name": "totalcashvalue_s",
            "baseName": "totalcashvalue-s",
            "type": "Summary"
        },
        {
            "name": "totaldebitcardpendingcharges",
            "baseName": "totaldebitcardpendingcharges",
            "type": "Summary"
        },
        {
            "name": "totaldebitcardpendingcharges_c",
            "baseName": "totaldebitcardpendingcharges-c",
            "type": "Summary"
        },
        {
            "name": "totaldebitcardpendingcharges_f",
            "baseName": "totaldebitcardpendingcharges-f",
            "type": "Summary"
        },
        {
            "name": "totaldebitcardpendingcharges_s",
            "baseName": "totaldebitcardpendingcharges-s",
            "type": "Summary"
        },
        {
            "name": "tradingtype_f",
            "baseName": "tradingtype-f",
            "type": "Summary"
        },
        {
            "name": "tradingtype_s",
            "baseName": "tradingtype-s",
            "type": "Summary"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20012.attributeTypeMap;
    }
}

