/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse20031String {
    /**
    * Outside of Regular Trading Hours
    */
    'ORTH'?: boolean;
    /**
    * Stop Price value
    */
    'SP'?: string;
    /**
    * Limit Price value
    */
    'LP'?: string;
    /**
    * Price Cap value
    */
    'PC'?: string;
    /**
    * Trailing amount value
    */
    'TA'?: string;
    /**
    * Trailing unit
    */
    'TU'?: string;
    /**
    * Releative offset amount
    */
    'ROA'?: string;
    /**
    * Relative offset percent
    */
    'ROP'?: string;
    /**
    * Touch trigger price
    */
    'TT'?: string;
    /**
    * Use Net Price for Bonds
    */
    'UNP'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ORTH",
            "baseName": "ORTH",
            "type": "boolean"
        },
        {
            "name": "SP",
            "baseName": "SP",
            "type": "string"
        },
        {
            "name": "LP",
            "baseName": "LP",
            "type": "string"
        },
        {
            "name": "PC",
            "baseName": "PC",
            "type": "string"
        },
        {
            "name": "TA",
            "baseName": "TA",
            "type": "string"
        },
        {
            "name": "TU",
            "baseName": "TU",
            "type": "string"
        },
        {
            "name": "ROA",
            "baseName": "ROA",
            "type": "string"
        },
        {
            "name": "ROP",
            "baseName": "ROP",
            "type": "string"
        },
        {
            "name": "TT",
            "baseName": "TT",
            "type": "string"
        },
        {
            "name": "UNP",
            "baseName": "UNP",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20031String.attributeTypeMap;
    }
}

