/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* device
*/
export class InlineResponse2004E {
    /**
    * device name
    */
    'NM'?: string;
    /**
    * device id
    */
    'I'?: string;
    /**
    * unique device id
    */
    'UI'?: string;
    /**
    * device is enabled or not 0-true, 1-false.
    */
    'A'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "NM",
            "baseName": "NM",
            "type": "string"
        },
        {
            "name": "I",
            "baseName": "I",
            "type": "string"
        },
        {
            "name": "UI",
            "baseName": "UI",
            "type": "string"
        },
        {
            "name": "A",
            "baseName": "A",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2004E.attributeTypeMap;
    }
}

