/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject7 {
    /**
    * alert id(order id)
    */
    'alertId'?: number;
    /**
    * 1 to activate, 0 to deactivate
    */
    'alertActive'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "alertId",
            "baseName": "alertId",
            "type": "number"
        },
        {
            "name": "alertActive",
            "baseName": "alertActive",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject7.attributeTypeMap;
    }
}

