/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse20033 {
    'server_id'?: string;
    'column_name'?: string;
    'symbol'?: string;
    'conidex'?: string;
    'con_id'?: number;
    'available_chart_periods'?: string;
    'company_name'?: string;
    'contract_description_1'?: string;
    'listing_exchange'?: string;
    'sec_type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "server_id",
            "baseName": "server_id",
            "type": "string"
        },
        {
            "name": "column_name",
            "baseName": "column_name",
            "type": "string"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string"
        },
        {
            "name": "conidex",
            "baseName": "conidex",
            "type": "string"
        },
        {
            "name": "con_id",
            "baseName": "con_id",
            "type": "number"
        },
        {
            "name": "available_chart_periods",
            "baseName": "available_chart_periods",
            "type": "string"
        },
        {
            "name": "company_name",
            "baseName": "company_name",
            "type": "string"
        },
        {
            "name": "contract_description_1",
            "baseName": "contract_description_1",
            "type": "string"
        },
        {
            "name": "listing_exchange",
            "baseName": "listing_exchange",
            "type": "string"
        },
        {
            "name": "sec_type",
            "baseName": "sec_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20033.attributeTypeMap;
    }
}

