/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InlineResponse20032Locations } from './inlineResponse20032Locations';

export class InlineResponse20032LocationTree {
    'display_name'?: string;
    'type'?: string;
    'locations'?: Array<InlineResponse20032Locations>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "display_name",
            "baseName": "display_name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<InlineResponse20032Locations>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20032LocationTree.attributeTypeMap;
    }
}

