/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject5 {
    'acctIds'?: Array<string>;
    'conids'?: Array<number>;
    /**
    * optional defaults to USD.
    */
    'currency'?: string;
    /**
    * optional, default value is 90
    */
    'days'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "acctIds",
            "baseName": "acctIds",
            "type": "Array<string>"
        },
        {
            "name": "conids",
            "baseName": "conids",
            "type": "Array<number>"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "days",
            "baseName": "days",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject5.attributeTypeMap;
    }
}

