/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IbcustEntityInfoEntities } from './ibcustEntityInfoEntities';

export class InlineResponse20010 {
    'applicantId'?: number;
    'entities'?: Array<IbcustEntityInfoEntities>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "applicantId",
            "baseName": "applicantId",
            "type": "number"
        },
        {
            "name": "entities",
            "baseName": "entities",
            "type": "Array<IbcustEntityInfoEntities>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20010.attributeTypeMap;
    }
}

