/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InlineResponse20035Schedules } from './inlineResponse20035Schedules';

export class InlineResponse20035 {
    'id'?: string;
    /**
    * null is returned.
    */
    'tradeVenueId'?: string;
    /**
    * Always contains at least one \'tradingTime\'  and zero or more \'sessionTime\' tags
    */
    'schedules'?: Array<InlineResponse20035Schedules>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "tradeVenueId",
            "baseName": "tradeVenueId",
            "type": "string"
        },
        {
            "name": "schedules",
            "baseName": "schedules",
            "type": "Array<InlineResponse20035Schedules>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20035.attributeTypeMap;
    }
}

