/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* If the LIQUID equitiesMarketHours differs from the total trading day then a separate \'session\' tag is returned.
*/
export class InlineResponse20035Sessions {
    'openingTime'?: number;
    'closingTime'?: number;
    /**
    * If the whole trading day is considered LIQUID then the value \'LIQUID\' is returned.
    */
    'prop'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "openingTime",
            "baseName": "openingTime",
            "type": "number"
        },
        {
            "name": "closingTime",
            "baseName": "closingTime",
            "type": "number"
        },
        {
            "name": "prop",
            "baseName": "prop",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20035Sessions.attributeTypeMap;
    }
}

