/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Returns tradingTime in exchange time zone.
*/
export class InlineResponse20035TradingTimes {
    'openingTime'?: number;
    'closingTime'?: number;
    'cancelDayOrders'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "openingTime",
            "baseName": "openingTime",
            "type": "number"
        },
        {
            "name": "closingTime",
            "baseName": "closingTime",
            "type": "number"
        },
        {
            "name": "cancelDayOrders",
            "baseName": "cancelDayOrders",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20035TradingTimes.attributeTypeMap;
    }
}

