/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse2001 {
    /**
    * optional, if A doesn\'t exist, it means user can\'t toggle this option. 0-off, 1-on.
    */
    'A'?: number;
    /**
    * fyi code
    */
    'FC'?: string;
    /**
    * disclaimer read, 1 = yes, = 0 no.
    */
    'H'?: number;
    /**
    * detailed description
    */
    'FD'?: string;
    /**
    * title
    */
    'FN'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "A",
            "baseName": "A",
            "type": "number"
        },
        {
            "name": "FC",
            "baseName": "FC",
            "type": "string"
        },
        {
            "name": "H",
            "baseName": "H",
            "type": "number"
        },
        {
            "name": "FD",
            "baseName": "FD",
            "type": "string"
        },
        {
            "name": "FN",
            "baseName": "FN",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2001.attributeTypeMap;
    }
}

