/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InlineResponse20032FilterList } from './inlineResponse20032FilterList';
import { InlineResponse20032InstrumentList } from './inlineResponse20032InstrumentList';
import { InlineResponse20032LocationTree } from './inlineResponse20032LocationTree';
import { InlineResponse20032ScanTypeList } from './inlineResponse20032ScanTypeList';

export class InlineResponse20032 {
    'scan_type_list'?: Array<InlineResponse20032ScanTypeList>;
    'instrument_list'?: Array<InlineResponse20032InstrumentList>;
    'filter_list'?: Array<InlineResponse20032FilterList>;
    'location_tree'?: Array<InlineResponse20032LocationTree>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "scan_type_list",
            "baseName": "scan_type_list",
            "type": "Array<InlineResponse20032ScanTypeList>"
        },
        {
            "name": "instrument_list",
            "baseName": "instrument_list",
            "type": "Array<InlineResponse20032InstrumentList>"
        },
        {
            "name": "filter_list",
            "baseName": "filter_list",
            "type": "Array<InlineResponse20032FilterList>"
        },
        {
            "name": "location_tree",
            "baseName": "location_tree",
            "type": "Array<InlineResponse20032LocationTree>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20032.attributeTypeMap;
    }
}

