/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class IserverSecdefSearchSections {
    /**
    * Asset Class
    */
    'secType'?: string;
    /**
    * List of expiration month(s) and year(s) in MMMYY format separated by semicolon
    */
    'months'?: string;
    'symbol'?: string;
    /**
    * Listing Exchange
    */
    'exchange'?: string;
    /**
    * For combo\'s defines the asset class for each leg
    */
    'legSecType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "secType",
            "baseName": "secType",
            "type": "string"
        },
        {
            "name": "months",
            "baseName": "months",
            "type": "string"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string"
        },
        {
            "name": "exchange",
            "baseName": "exchange",
            "type": "string"
        },
        {
            "name": "legSecType",
            "baseName": "legSecType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IserverSecdefSearchSections.attributeTypeMap;
    }
}

