/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Ledger {
    'commoditymarketvalue'?: number;
    'futuremarketvalue'?: number;
    'settledcash'?: number;
    'exchangerate'?: number;
    'sessionid'?: number;
    'cashbalance'?: number;
    'corporatebondsmarketvalue'?: number;
    'warrantsmarketvalue'?: number;
    'netliquidationvalue'?: number;
    'interest'?: number;
    'unrealizedpnl'?: number;
    'stockmarketvalue'?: number;
    'moneyfunds'?: number;
    'currency'?: string;
    'realizedpnl'?: number;
    'funds'?: number;
    'acctcode'?: string;
    'issueroptionsmarketvalue'?: number;
    'key'?: string;
    'timestamp'?: number;
    'severity'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commoditymarketvalue",
            "baseName": "commoditymarketvalue",
            "type": "number"
        },
        {
            "name": "futuremarketvalue",
            "baseName": "futuremarketvalue",
            "type": "number"
        },
        {
            "name": "settledcash",
            "baseName": "settledcash",
            "type": "number"
        },
        {
            "name": "exchangerate",
            "baseName": "exchangerate",
            "type": "number"
        },
        {
            "name": "sessionid",
            "baseName": "sessionid",
            "type": "number"
        },
        {
            "name": "cashbalance",
            "baseName": "cashbalance",
            "type": "number"
        },
        {
            "name": "corporatebondsmarketvalue",
            "baseName": "corporatebondsmarketvalue",
            "type": "number"
        },
        {
            "name": "warrantsmarketvalue",
            "baseName": "warrantsmarketvalue",
            "type": "number"
        },
        {
            "name": "netliquidationvalue",
            "baseName": "netliquidationvalue",
            "type": "number"
        },
        {
            "name": "interest",
            "baseName": "interest",
            "type": "number"
        },
        {
            "name": "unrealizedpnl",
            "baseName": "unrealizedpnl",
            "type": "number"
        },
        {
            "name": "stockmarketvalue",
            "baseName": "stockmarketvalue",
            "type": "number"
        },
        {
            "name": "moneyfunds",
            "baseName": "moneyfunds",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "realizedpnl",
            "baseName": "realizedpnl",
            "type": "number"
        },
        {
            "name": "funds",
            "baseName": "funds",
            "type": "number"
        },
        {
            "name": "acctcode",
            "baseName": "acctcode",
            "type": "string"
        },
        {
            "name": "issueroptionsmarketvalue",
            "baseName": "issueroptionsmarketvalue",
            "type": "number"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "severity",
            "baseName": "severity",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Ledger.attributeTypeMap;
    }
}

