/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ModifyOrder {
    'acctId'?: string;
    'conid'?: number;
    /**
    * for example LMT
    */
    'orderType'?: string;
    'outsideRTH'?: boolean;
    'price'?: number;
    'auxPrice'?: number;
    /**
    * SELL or BUY
    */
    'side'?: string;
    /**
    * optional, not required
    */
    'listingExchange'?: string;
    'ticker'?: string;
    /**
    * for example DAY
    */
    'tif'?: string;
    /**
    * usually integer, for some special cases can be float numbers
    */
    'quantity'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "acctId",
            "baseName": "acctId",
            "type": "string"
        },
        {
            "name": "conid",
            "baseName": "conid",
            "type": "number"
        },
        {
            "name": "orderType",
            "baseName": "orderType",
            "type": "string"
        },
        {
            "name": "outsideRTH",
            "baseName": "outsideRTH",
            "type": "boolean"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "auxPrice",
            "baseName": "auxPrice",
            "type": "number"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "string"
        },
        {
            "name": "listingExchange",
            "baseName": "listingExchange",
            "type": "string"
        },
        {
            "name": "ticker",
            "baseName": "ticker",
            "type": "string"
        },
        {
            "name": "tif",
            "baseName": "tif",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ModifyOrder.attributeTypeMap;
    }
}

