/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* contains all the order related info
*/
export class Order {
    /**
    * account id
    */
    'acct'?: string;
    'conid'?: number;
    'orderDesc'?: string;
    'description1'?: string;
    /**
    * for exmple FB
    */
    'ticker'?: string;
    /**
    * for example STK
    */
    'secType'?: string;
    /**
    * for example NASDAQ.NMS
    */
    'listingExchange'?: string;
    'remainingQuantity'?: string;
    'filledQuantity'?: string;
    'companyName'?: string;
    /**
    * PendingSubmit - Indicates the order was sent, but confirmation has not been received that it has been received by the destination.                  Occurs most commonly if an exchange is closed. PendingCancel - Indicates that a request has been sent to cancel an order but confirmation has not been received of its cancellation. PreSubmitted - Indicates that a simulated order type has been accepted by the IBKR system and that this order has yet to be elected.                 The order is held in the IBKR system until the election criteria are met. At that time the order is transmitted to the order destination as specified.  Submitted - Indicates that the order has been accepted at the order destination and is working. Cancelled - Indicates that the balance of the order has been confirmed cancelled by the IB system.              This could occur unexpectedly when IB or the destination has rejected the order.   Filled - Indicates that the order has been completely filled.  Inactive - Indicates the order is not working, for instance if the order was invalid and triggered an error message,            or if the order was to short a security and shares have not yet been located.  
    */
    'status'?: string;
    /**
    * for example Limit
    */
    'origOrderType'?: string;
    /**
    * BUY or SELL
    */
    'side'?: string;
    'price'?: number;
    /**
    * back-ground color
    */
    'bgColor'?: string;
    'fgColor'?: string;
    'orderId'?: number;
    /**
    * Only exists in child order of bracket
    */
    'parentId'?: number;
    /**
    * User defined string used to identify the order. Value is set using \"cOID\" field while placing an order.
    */
    'order_ref'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "acct",
            "baseName": "acct",
            "type": "string"
        },
        {
            "name": "conid",
            "baseName": "conid",
            "type": "number"
        },
        {
            "name": "orderDesc",
            "baseName": "orderDesc",
            "type": "string"
        },
        {
            "name": "description1",
            "baseName": "description1",
            "type": "string"
        },
        {
            "name": "ticker",
            "baseName": "ticker",
            "type": "string"
        },
        {
            "name": "secType",
            "baseName": "secType",
            "type": "string"
        },
        {
            "name": "listingExchange",
            "baseName": "listingExchange",
            "type": "string"
        },
        {
            "name": "remainingQuantity",
            "baseName": "remainingQuantity",
            "type": "string"
        },
        {
            "name": "filledQuantity",
            "baseName": "filledQuantity",
            "type": "string"
        },
        {
            "name": "companyName",
            "baseName": "companyName",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "origOrderType",
            "baseName": "origOrderType",
            "type": "string"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "bgColor",
            "baseName": "bgColor",
            "type": "string"
        },
        {
            "name": "fgColor",
            "baseName": "fgColor",
            "type": "string"
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "number"
        },
        {
            "name": "parentId",
            "baseName": "parentId",
            "type": "number"
        },
        {
            "name": "order_ref",
            "baseName": "order_ref",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Order.attributeTypeMap;
    }
}

