/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ScannerParamsFilter } from './scannerParamsFilter';

export class ScannerParams {
    /**
    * for example-STK
    */
    'instrument'?: string;
    /**
    * for example-TOP_PERC_GAIN
    */
    'type'?: string;
    'filter'?: Array<ScannerParamsFilter>;
    'location'?: string;
    'size'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "instrument",
            "baseName": "instrument",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "Array<ScannerParamsFilter>"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ScannerParams.attributeTypeMap;
    }
}

