/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ScannerResultContractsContract } from './scannerResultContractsContract';

/**
* Contains list of contracts matching the scanner query
*/
export class ScannerResultContracts {
    'Contract'?: Array<ScannerResultContractsContract>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "Contract",
            "baseName": "Contract",
            "type": "Array<ScannerResultContractsContract>"
        }    ];

    static getAttributeTypeMap() {
        return ScannerResultContracts.attributeTypeMap;
    }
}

