/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ScannerResultContracts } from './scannerResultContracts';

export class ScannerResult {
    'total'?: number;
    'size'?: number;
    'offset'?: number;
    'scanTime'?: string;
    'id'?: number;
    'position'?: string;
    'Contracts'?: ScannerResultContracts;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number"
        },
        {
            "name": "scanTime",
            "baseName": "scanTime",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "string"
        },
        {
            "name": "Contracts",
            "baseName": "Contracts",
            "type": "ScannerResultContracts"
        }    ];

    static getAttributeTypeMap() {
        return ScannerResult.attributeTypeMap;
    }
}

