/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Contains some basic info of contract
*/
export class SecdefInfo {
    'conid'?: number;
    /**
    * For example IBKR
    */
    'symbol'?: string;
    'secType'?: string;
    'exchange'?: string;
    'listingExchange'?: string;
    /**
    * C = Call Option, P = Put Option
    */
    'right'?: string;
    /**
    * The strike price also known as exercise price
    */
    'strike'?: string;
    /**
    * Currency the contract trades in
    */
    'currency'?: string;
    /**
    * Committee on Uniform Securities Identification Procedures number
    */
    'cusip'?: string;
    /**
    * Annual interest rate paid on a bond
    */
    'coupon'?: string;
    /**
    * Formatted symbol
    */
    'desc1'?: string;
    /**
    * Formatted expiration, strike and right
    */
    'desc2'?: string;
    /**
    * Format YYYYMMDD, the date on which the underlying transaction settles if the option is exercised
    */
    'maturityDate'?: string;
    /**
    * total premium paid or received for an option contract
    */
    'multiplier'?: string;
    'tradingClass'?: string;
    'validExchanges'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "conid",
            "baseName": "conid",
            "type": "number"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string"
        },
        {
            "name": "secType",
            "baseName": "secType",
            "type": "string"
        },
        {
            "name": "exchange",
            "baseName": "exchange",
            "type": "string"
        },
        {
            "name": "listingExchange",
            "baseName": "listingExchange",
            "type": "string"
        },
        {
            "name": "right",
            "baseName": "right",
            "type": "string"
        },
        {
            "name": "strike",
            "baseName": "strike",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "cusip",
            "baseName": "cusip",
            "type": "string"
        },
        {
            "name": "coupon",
            "baseName": "coupon",
            "type": "string"
        },
        {
            "name": "desc1",
            "baseName": "desc1",
            "type": "string"
        },
        {
            "name": "desc2",
            "baseName": "desc2",
            "type": "string"
        },
        {
            "name": "maturityDate",
            "baseName": "maturityDate",
            "type": "string"
        },
        {
            "name": "multiplier",
            "baseName": "multiplier",
            "type": "string"
        },
        {
            "name": "tradingClass",
            "baseName": "tradingClass",
            "type": "string"
        },
        {
            "name": "validExchanges",
            "baseName": "validExchanges",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SecdefInfo.attributeTypeMap;
    }
}

