/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class StatsData {
    'Conid'?: number;
    'Exchange'?: string;
    'V'?: number;
    'T'?: number;
    'TT'?: number;
    /**
    * Object, payload depends on event type. See confluence page for IGEvntUpd.
    */
    'P'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "Conid",
            "baseName": "Conid",
            "type": "number"
        },
        {
            "name": "Exchange",
            "baseName": "Exchange",
            "type": "string"
        },
        {
            "name": "V",
            "baseName": "V",
            "type": "number"
        },
        {
            "name": "T",
            "baseName": "T",
            "type": "number"
        },
        {
            "name": "TT",
            "baseName": "TT",
            "type": "number"
        },
        {
            "name": "P",
            "baseName": "P",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StatsData.attributeTypeMap;
    }
}

