/**
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TransactionsTransactions {
    'acctid'?: string;
    'conid'?: number;
    /**
    * currency code
    */
    'cur'?: string;
    /**
    * Conversion rate from asset currency to response currency
    */
    'fxRate'?: number;
    /**
    * Transaction description
    */
    'desc'?: string;
    /**
    * Date of transaction.  Epoch time, GMT
    */
    'date'?: string;
    /**
    * Transaction OptType Name: Examples: \"Sell\", \"Buy\", \"Corporate Action\", \"Dividend Payment\", \"Transfer\", \"Payment in Lieu\" Dividends and Transfers do not have price and quantity in response
    */
    'type'?: string;
    /**
    * Not applicable for all transaction types
    */
    'qty'?: number;
    /**
    * In asset currency. Not be applicable for all transaction types.
    */
    'pr'?: number;
    /**
    * Raw value, no formatting. Net transaction amount (may include commission, tax). In asset currency
    */
    'amt'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "acctid",
            "baseName": "acctid",
            "type": "string"
        },
        {
            "name": "conid",
            "baseName": "conid",
            "type": "number"
        },
        {
            "name": "cur",
            "baseName": "cur",
            "type": "string"
        },
        {
            "name": "fxRate",
            "baseName": "fxRate",
            "type": "number"
        },
        {
            "name": "desc",
            "baseName": "desc",
            "type": "string"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "qty",
            "baseName": "qty",
            "type": "number"
        },
        {
            "name": "pr",
            "baseName": "pr",
            "type": "number"
        },
        {
            "name": "amt",
            "baseName": "amt",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TransactionsTransactions.attributeTypeMap;
    }
}

